[package]
name = "router-info"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
ipnetwork = "0.20"
pnet = "0.31"
serde = { version = "1.0", features = ["derive"] }
